### ISSUE TITLE
⭐ New feature: Integration of this report with existing framework

### ISSUE THREAD

**Issue by manjunath-ZEE** [WasiqB/ultra-reporter-app#51]
### 📗 Description of the new feature request?

 I have installed ultra-report using npm command. I am trying to integrate this with my existing java testNg framework. I want to genarate this report along with my execution. While trying getting the below error while same is working fine if the xml uploaded in UI.
 
  @WasiqB Please suggest is there any other way to integrate and use this reporting in existing frame work
 
 ultra-report target/surefire-reports/testng-results.xml

✔ XML File exists
✖️ Error while generating JSON from XML

Message: TypeError - Cannot read properties of undefined (reading 'ignored')

ℹ If you feel the issue is related to the report, please open an issue on GitHub 👇
🔗 https://github.com/WasiqB/ultra-report/issues/new

**Comment by WasiqB** [comment]
Hi @manjunath-ZEE , Thank you for taking the time to create this issue.

Can you please clarify which project are you trying to use?

Ultra-report, a CLI app or this project, Ultra-reporter-app, a Web app?

Just to clarify, I am not maintaining Ultra-report CLI app any more, because Next JS is lacking support for generating static HTML files from command line.

I had already opened [a discussion](https://github.com/vercel/next.js/discussions/70310) about the same in NextJS repo, but did not got any response from them, hence created this Web app.

For using this app, you just need to use TestNG's default reporter listener to generate the XMl file.

Check out [this video](https://youtu.be/l2pk7LAq50I?si=YmoV0JKedQBwPStj), to know how to use this report.

This ticket is now being closed because it is not related to this project.

Let me know if you have any suggestions for this application after you have explored it.

**Comment by manjunath-ZEE** [comment]
Hi @WasiqB thanks for your swift reply. 

Could you please help me how can I integrate your project into my existing framework. Please note I don't want to upload the XML file in browser UI to generate report. I want to use your code to generate the report internally. Please help
