### ISSUE TITLE
🐛 New Bug: Miscellaneous UI issues

### ISSUE THREAD

**Issue by PadmalochanMurmu12** [WasiqB/ultra-reporter-app#63]
### ❓ What is the bug?

UI needs to be more concise and responsive with respect to the screen resolution

### 📃 Steps to reproduce the bug

Switch to 1366*768 resolution. And take care of the following changes

### ✅ Expected Behavior

1. Increase the top padding of the Test Statistics <div/> https://prnt.sc/siy7-LDUnNfh and adjust the padding of  Test Summary Counts and Test Summary % <div/> accordingly
2. Decrease the size of the Test Execution Trends (in seconds) Graph so that we do not need to scroll down to see the full graph https://prnt.sc/WJzEC6HLXqC4
3. Rows per page option can be started from 5 rather than 10 for better User experience. https://prnt.sc/y1_fh3DGES8g
4. The + icon should be replaced with the dropdown icon to distinguish the filter easily. As it looks like Creating new status rather than Filtering out the status of the test https://prnt.sc/vv_xxGQiDE4_

### ❌ Actual Behavior

The UI doesn't look that appealing in smalled screens

**Comment by WasiqB** [comment]
@PadmalochanMurmu12 , thanks for sharing the feedback. Will look into this in the next Milestone.

**Comment by WasiqB** [comment]
- Increase the top padding of the Test Statistics
https://prnt.sc/siy7-LDUnNfh and adjust the padding of Test Summary Counts and Test Summary %accordingly, **_[WB]: Fixed_**
- Decrease the size of the Test Execution Trends (in seconds) Graph so that we do not need to scroll down to see the full graph https://prnt.sc/WJzEC6HLXqC4, **_[WB]: Will be handled when a new chart would be added next to this. Currently it automatically calculates the height and width based on the area it has to utilise._**
- Rows per page option can be started from 5 rather than 10 for better User experience. https://prnt.sc/y1_fh3DGES8g. **_[WB]: Will be handled in the future._**
- The + icon should be replaced with the dropdown icon to distinguish the filter easily. As it looks like Creating new status rather than Filtering out the status of the test https://prnt.sc/vv_xxGQiDE4_. **_[WB]: Since the status button lies on the filter toolbar, it makes sense with a plus icon to add the status filter to existing filter criteria._**
